### ISSUE TITLE
remove remote main

### ISSUE THREAD

**Issue by Chaotique** [AdriaMeca/data_analysis#1]
Dear Adria,
in your case it now would make sense to delete main, as master is actually your central branch.
Therefore at first, make master your default branch on github.com: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

If you have main also locally, type this locally:

git checkout master
git branch -d main
git push origin --delete main

Otherwise (if you don't have a local branch main), just delete the main branch on github.com: go to the list of branches, click "View all branches", and delete main.

Task done. Congrats!
All the best,
Chaotique

**Comment by AdriaMeca** [comment]
Hi Franziska, I've solved the problem with the different default branches.
